name: check-build,

on: [pull_request]
  
jobs:
  init: 
     runs-on: ubuntu-latest
   
     steps:             
        - name: init-app
          run: |
               pwd
               ls
               yarn init --yes
               yarn lint
          
          
