name: check-build

on: [pull_request]

jobs:
   eslint: 
     runs-on: ubuntu-latest
   
     steps: 
        - name: go-to-app
          run: cd stepsApp/
        - name: check-lint
          run: yarn lint
          
            
